title: Sarah Strickman
subtitle: A Personal Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://jekyll.sarahstrickman.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
#    - text: Gallery
#      url: /gallery
#    - text: Shop
#      url : /shop
#    - text: Contact
#      url : /contact
#    - text: Styleguide
#      url: /styleguide
#    - text: Get Started
#      url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author-profile-img: portrait-scowl.jpg
author_logo: portrait-scowl.jpg
author: Sarah Strickman
author_bio: Hi, I'm Sarah.  I do things sometimes.
author_email: "sarahstrickman@gmail.com"
author_location: New York
author_website_url: "https://sarahstrickman.com"
typewrite-text: This is a personal site made using the developr jekyll theme template

# Experiences
author_work_experiences:
            - company_name: RIT Computer Science Department
              company_logo: rit-logo.png
              company_url: https://www.rit.edu/computing/department-computer-science
              designation: Student Lab Instructor
              description: >-
                <ul>
                <li>Works with professors in brainstorming problem-solving sessions once a week.</li>
                <li>Leads students in problem solving sessions and guides them to understanding introductory computing concepts.</li>
                <li>Mentors for 2 hours every week to help students understand concepts and complete assignments.</li>
                <li>Grades and provides feedback on weekly lab submissions from students.</li>
                <li>Courses taught: Computer Science 1 (CSCI-141), Computer Science for AP/Transfers (CSCI-242), Computer Science 2 (CSCI-142)</li>
                </ul>
              visibility: true

            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Software Engineering Intern
              description: >-
                Wrote a rule based troubleshooting tool for the Bing Platform Microservices team.<br><br>
                Participated in the full lifecycle of the tool by:<br><br>
                <ul>
                <li>surveying customers and analyzing logs using MQL and KQL</li>
                <li>designing a modular and easily extendable tool utilizing Singleton and Dependency Injection patterns</li>
                <li>writing and unit testing the tool C# and APS.NET Core</li>
                </ul>
              visibility: true

            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Explore Intern
              description: >-
                <ul>
                <li>Worked within the Microsoft Ads Editor (MAE) team to develop a feature that better allowed users to take advantage of newly released features.</li>
                <li>Wrote a functional requirements spec detailing how the feature should appear to the user, how it would be integrated within MAE, and how developers would use the feature.</li>
                <li>Used React, CSS, and C# to handle communication from the client and server sides of the application, as well as to write how the feature would appear in MAE.</li>
                <li>Wrote extensive tests for the feature to ensure that its integration in MAE is seamless. Maintained a code coverage of over 93% for every part of the feature.</li>
                </ul>
              visibility: true

# Education
author_education_details:
              - college_logo: rit-logo.png
                college_name: RIT
                college_url: https://rit.edu
                college_degree: Computer Science and Software Engineering
                description: Bachelor of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true

              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: sarahstrickman
github_username:  sarahstrickman
facebook_username: sarah.e.strickman
linkedin_username: sarahstrickman
#behance_username: johndoe
#instagram_username: sarah.strickman
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter): # UNUSED
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: sarahstrickman@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
